#!/bin/bash

set -e
        
# OVERVIEW
# This script installs a jupyterlab extension package in SageMaker Notebook Instance
sudo -u ec2-user -i <<'EOF'
   # PARAMETERS
   ALMOND_VERSION=0.10.9
   SCALA_VERSION=2.12.12
   JAVA_HOME=/home/ec2-user/anaconda3/envs/JupyterSystemEnv
   PATH=$JAVA_HOME/bin:$PATH
   cd /tmp
   curl -Lo coursier https://git.io/coursier-cli
   chmod +x coursier
   ./coursier launch --fork almond:$ALMOND_VERSION --scala $SCALA_VERSION -- --install --force
   rm -f coursier
   source /home/ec2-user/anaconda3/bin/activate JupyterSystemEnv
   jupyter labextension install jupyterlab-plotly
   source /home/ec2-user/anaconda3/bin/deactivate
EOF
